### ISSUE TITLE
Reference field count

### ISSUE THREAD

**Issue by katiedahl** [slifty/tvarchive-canonical_wordpress#103]
there seems to be some kind of glitch with the reference field in the data. i downloaded the dataset to update a fact-check tracking spreadsheet @nancyw is using. every cell in the reference column, except for three of them, has at least a 1. but the first ten "1's" i checked did not have an associated fact-check.

**Comment by slifty** [comment]
This has been patched and will be deployed shortly; the patch was made over in the plugin repo: https://github.com/slifty/tvarchive-politicaladarchive_plugin/commit/111cbf4012d5fbf19d1eb1d9a10545d117eced82
