### ISSUE TITLE
Updated homepage explore

### ISSUE THREAD

**Issue by slifty** [slifty/tvarchive-canonical_wordpress#24]
We're going to implement an updated explore interface as shown https://projects.invisionapp.com/share/BQ7B3D4CM#/screens/158693517

(Note, this has been started already by @danletson but his hasn't been approved yet since it needs to incorporate the updated design).

**Comment by danletson** [comment]
The mockup shows banding by race and party affiliation, but from what I can tell, the dataset for each ad only contains race and year. I did notice that the party affiliation of an ad's sponsor seems to be present in the data returned when the Opensecrets API is queried for sponsors?

Line 559 of plugins/tvarchive-politicalads/tvarchive-politicalads.php: 
// Candidates have the party as part of the name

Not sure exactly how that could be mapped to candidates, but it might be helpful...

As far as the races go, how much work is it to modify the get_candidate() function to return the ad_race as a property of the candidate? Should I take a crack at it myself?

Also, if this is not the place for these types of questions/discussion, let me know :)

**Comment by slifty** [comment]
You are correct!  I need to add party affiliation to the dataset during the CRP sync -- as for race, take a crack at adding it but if you get stuck just mock that in and I'll include it when I do affiliation.

**Comment by slifty** [comment]
The actual design for this is implemented, but needs to be updated to use the new plugin.  @danletson will be issuing a new PR for review this week.

**Comment by slifty** [comment]
The functionality itself is wrapped up -- there are some tweaks needed but they are already captured by other issues (Issue #42 in particular)
