### ISSUE TITLE
resolve problem w/ "market" v. "location"

### ISSUE THREAD

**Issue by nwatzmanco** [slifty/tvarchive-canonical_wordpress#55]
Current "market" descriptions are single cities, which are not names of markets. This is confusing for users who don't necessarily know, for example, that Boston = New Hampshire. We need to display the Nielsen market names for the "market" visualizations. Here is a link to Nielsen market names:

http://www.nielsen.com/content/dam/corporate/us/en/public%20factsheets/tv/2016-local-television-market-universe-estimates.pdf

Alternatively, we could change the word "market" in visualization to "location," and then the display is for the city/state where our recording info is located. 

We should talk this through.

**Comment by slifty** [comment]
Update: Eventually this should be looked up from the internet archive, which is where the codes are applied and determined.  Until then we have a hard coded list which appears in two places:
1. In the logic around sync
2. In the logic around the market map

This means whenever we add a new market we need to manually add it to those two locations.

The list today is as follows:
            "BOS" => "Boston, MA/Manchester, NH",
            "CAE" => "Columbia, SC",
            "CID" => "Ceder Rapids-Waterloo-Iowa City-Dublin, Iowa",
            "CLE" => "Cleveland, Ohio",
            "CLT" => "Charlotte, NC",
            "COS" => "Colorado Springs-Pueblo, CO",
            "CVG" => "Cincinnati, OH",
            "DEN" => "Denver, CO",
            "DSM" => "Des Moines-Ames, Iowa",
            "GSP" => "Greenville-Spartanburg, SC/Asheville-Anderson, NC",
            "LAS" => "Las Vegas, NV",
            "MCO" => "Orlando-Daytona Beach-Melbourne, FL",
            "MIA" => "Miami-Fort Lauderdale, FL",
            "NYC" => "New York City, NY",
            "ORF" => "Norfolk-Portsmouth-Newport News, NC",
            "PHL" => "Philadelphia, PA",
            "RDU" => "Raleigh-Durham-Fayetteville,  NC",
            "RNO" => "Reno, NV",
            "ROA" => "Roanoke-Lynchburg, VA",
            "SF" =>  "San Francisco-Oakland-San Jose, CA",
            "SUX" => "Sioux City, Iowa",
            "TPA" => "Tampa-St. Petersburg, FL",
            "VA" =>  "Washington, DC/Hagerstown, MD"

What are the extras that we need to add in for this phase?

**Comment by slifty** [comment]
I'm going to mark this issue as resolved since we addressed the immediate issue
